### PR TITLE
Added scaladoc to Identifier with some placesholders

### PR DESCRIPTION
**Pull request by Mironor**
Can you, please, explain what to put in the places where I have "???" ? It's some Scala magic that I didn't use before and that I currently don't understand.

Thanks!

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
Sure. Scala's `TypeTag` is the way to get a generic type's meta-information at the runtime. When you use something like `inject [Foo]` library needs to know information about the `Foo` type at the runtime in order to construct an Identifier for it and then inject instance of this type. `TypeTag` type class allows one to do this.

I can recommend following part of the docs for more info:

http://docs.scala-lang.org/overviews/reflection/typetags-manifests.html

BTW, I would avoid term "cast" because there is no casting taking place in this code. I would say something like "transform", "covert" or "use" is more suitable here.

For instance:

```scala
  /**
     * Defines an evidence that `scala.Symbol` can be used as an `scaldi.Identifier`. `scala.Symbol` is mapped to a `scaldi.StringIdentifier`.
     */
    implicit object SymbolCanBeIdentifier extends CanBeIdentifier[Symbol] {
      def toIdentifier(sym: Symbol) = StringIdentifier(sym.name)
    }
```

Actually I'm not 100% sure that it's necessary to document these implicit implementations of a typeclasses. At least in trivial cases. But I may be wrong here, I guess some people may find it helpful.

**Comment by Mironor** [comment]
Ok, these are just reflections. 
Finished the scaladoc, imo documentation on type class methods are important (at least for me so that I could easily see for what types I could use the method)

**Comment by Mironor** [comment]
Hi Oleg,

It's been quite some time, do you think it is possible to merge this pull request or you consider it is not yet finished?

**Comment by OlegIlyenko** [comment]
Thank you very much! And I'm very sorry for keeping you wait for such a long time :( You should have kicked me :dizzy:  a bit earlier :)

**Pull request merged**
